global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'evid-flow-gateway'
    static_configs:
      - targets: ['api-gateway:8000']
    metrics_path: /metrics
    scrape_interval: 30s

  - job_name: 'evid-flow-auth'
    static_configs:
      - targets: ['auth-service:8001']
    metrics_path: /metrics
    scrape_interval: 30s

  - job_name: 'evid-flow-organizations'
    static_configs:
      - targets: ['org-service:8003']
    metrics_path: /metrics
    scrape_interval: 30s

  - job_name: 'evid-flow-beneficiaries'
    static_configs:
      - targets: ['beneficiary-service:8004']
    metrics_path: /metrics
    scrape_interval: 30s

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']
    metrics_path: /metrics
    scrape_interval: 30s

  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    metrics_path: /metrics
    scrape_interval: 30s
